SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
res = (SCREEN_WIDTH, SCREEN_HEIGHT)
JUMP_VELOCITY = 15
MAX_JUMP = 150

MENU_START_X = SCREEN_WIDTH / 4
MENU_START_Y = SCREEN_HEIGHT / 8

ARROW_HALF_HEIGHT = 33
ARROW_HALF_WIDTH = 43

GRAVITY = 1

GAME_CAPTION = 'Sky Jumper'

GRASS_RESISTANCE = 0.1

COIN_IMAGE = 'coin.png'
ARROW_IMAGE = 'arrow.png'
STORE_OPTIONS = ["JUMP BOOST 5 Coins", "EXTRA LIFE 10 Coins", "Confirm purchase"]
JUMP_BOOST_COST = 5
EXTRA_LIFE_COST = 10
